version: '3'
services:
  teamcitytheatre:
    container_name: tct
    image: teamcitytheatre
    ports:
    - 5000:80
    volumes:
    - ./config:/app/config
    - ./config/users:/app/wwwroot/users
    environment:
    - Connection:Url=https://teamcity.jetbrains.com
    - Connection:Username=guest
    - Connection:Password=
    - Storage:ConfigurationFile=/app/config/configuration.json
    - Serilog:1:Args:path=/app/config/logs/TeamCityTheatre.Web-.log